### PR TITLE
Update to released sdk 5.0.100

### PR DESCRIPTION
**Pull request by trivalik**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/try-convert?pullRequest=318) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/try-convert?pullRequest=318) before we can accept your contribution.<br/><br/>:x: trivalik [sign now](https://cla.dotnetfoundation.org/dotnet/try-convert?pullRequest=318)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/try-convert?pullRequest=318) it.</sub>

**Comment by cartermp** [comment]
Thanks for the contribution! I'll have to mull this over with @jmarolf. I did an update like this in a different PR before but there were some reasons not to depend on .NET 5 just yet. Perhaps we can revisit that decision, since it seems like it impacts being able to read projects with the .NET 5 SDK.

Absolutely bizarre that this worked without issue throughout previews and RCs but failed at release.

**Comment by cartermp** [comment]
I believe this would also resolve issues found here: https://github.com/dotnet/try-convert/pull/316

**Comment by augustoproiete** [comment]
I can confirm this PR fixed #317 & #320 for me and I was able to run `try-convert` against a number of `net4xx` projects and get them to `net5.0`

**Comment by cartermp** [comment]
Okay, so a downside of accepting this PR is that it would not allow try-convert to run on older SDKs. So if someone doesn't have the .NET 5 SDK (or can't install it for some reason), then the tool isn't possible for them to run.

An alternative is to get _fancy_ and implement a custom assembly load context like so: https://github.com/dotnet/msbuild/blob/master/src/Shared/MSBuildLoadContext.cs

**Comment by trivalik** [comment]
I am fine with if this is not accepted. I just want to use this tool to fast upgrade hundret of projects.

**Comment by cartermp** [comment]
@trivalik no worries! We'll have a think about how to move forward with this. Were you able to convert projects from a build based on this branch?

**Comment by rjk** [comment]
fyi I get this error when trying to build this PR: 

`C:\code\sandbox\try-convert\src\MSBuild.Conversion.Package\PackagesConfigParser.cs(72,26): error CS8602: Dereference of a possibly null reference. [C:\code\sandbox\try-convert\src\MSBuild.Conversion.Package\MSBuild.Conversion.Package.csproj]`

I'm guessing it's something environmental on my side since I've not built the project at all before and it seems to work for others here ... but thought I'd mention it anyway.

**Comment by trivalik** [comment]
@cartermp Yes, I converted a few hundred projects from .NET Framework 4.8. For sure I added by search and replace some issues, but it saves alot time. Thanks for your work!
@rjk I didnt try to build via "Build.cmd". But I updated the global.json just from preview to release of .net 5

**Comment by cartermp** [comment]
Thought about this a bit. We'll take this and push an update. try-convert will require the latest SDK, but that's probably fine. Thanks for the contribition!

**Review by cartermp — APPROVED** [review]

**Comment by rallets** [comment]
> fyi I get this error when trying to build this PR using build.cmd:
This happen to me too

**Pull request merged**
