### PR TITLE
Enable conversion of web projects

### PR DESCRIPTION
**Pull request by mjrousos**
Although we aren't able to completely migrate web projects to Core automatically, it can sometimes be useful to just get the project files updated to SDK-style in preparation for manual conversion later.

To support that, these changes enable converting web projects if the new `--force-web-conversion` parameter is used.

The changes are basically:

1.	Piping through the new command line parameter for opting into web project conversion.
2.	Making ProjectStyle.Web a project style that will be used if the project references System.Web.
3.	Using the Web SDK for projects with the web project style.
4.	Adding some additional ‘UnnecessaryProperties’ and ‘UnnecessaryItemIncludes’ to clean out web project elements that aren’t used in Core.
5.	Removing web extension elements.

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
Thanks!

**Comment by MaherJendoubi** [comment]
@mjrousos Thank you for implementing this feature. I compiled your PR and I tested the try-convert with --force-web-conversion
but my project is still not converted. I still have the message: "Foo.csproj contains a reference to System.Web, which is not supported on .NET Core. You may have significant work ahead of you to fully port this project."

**Comment by mjrousos** [comment]
@MaherJendoubi, that message is expected. I left that warning in because it's still true. Even with this change, migrating an ASP.NET project to ASP.NET Core will require a lot of additional work beyond running this tool. 

You'll still need to update your startup code paths, change configuration, update controllers and views to use different APIs, etc. This change just takes care of the first step of that process (changing the format of the project file).

Did you csproj update to an SDK-style project despite that warning? If the csproj didn't change, then something's up. The warning itself, though, is expected.

**Comment by MaherJendoubi** [comment]
@mjrousos my csproj was not changed.

**Comment by MaherJendoubi** [comment]
@mjrousos I could share with you a repro if needed.

**Comment by mjrousos** [comment]
That would be great. Thanks, @MaherJendoubi. If you can share a repro, I'll investigate.

**Comment by MaherJendoubi** [comment]
@mjrousos  Here you go : 

1. git clone https://github.com/ClearCanvas/ClearCanvas
2. git clone https://github.com/ClearCanvas/ReferencedAssemblies
3. cd ClearCanvas
4. mklink ReferencedAssemblies ..\ReferencedAssemblies
5. cd ImageViewer
6. C:\Users\xxx\Documents\GitHub\try-convert\artifacts\bin\try-convert\Debug\net5.0\try-convert --force-web-conversion -w ImageViewer.sln

**Comment by MaherJendoubi** [comment]
The libraries ClearCanvas.Common and ClearCanvas.Dicom contain a System.Web reference. That's why they remain not converted.

**Comment by mjrousos** [comment]
Thanks! I'm back in the office Tuesday and will take a look then.

**Comment by mjrousos** [comment]
@MaherJendoubi, I took a look at ClearCanvas. It's failing to convert, but not because of the System.Web reference. When I try to run try-convert on ClearCanvas.Common, I get this output:

```
This project has custom imports that are not accepted by try-convert.
Unexpected custom imports were found:
        ClearCanvas.Strings.targets
```

Try-convert won't convert projects that have custom targets. I think this is done because custom targets may not work with SDK-style projects, so the tool forces users to migrate them manually. @cartermp, can you confirm this is the thinking there?

If I comment out the ClearCanvas.Strings.targets import, Try-Convert successfully migrates the project file to a netstandard2.0-targeted library using the Web SDK, as expected.

**Comment by cartermp** [comment]
Yes, that's correct. I suspect there is some potential leeway we can have here, perhaps via a compiler switch. I was loathe to add one in the past but it might be worthwhile.

**Comment by mjrousos** [comment]
Makes sense. I agree this one is a good item to keep an eye on. Things are probably ok as they are for the time being, but if a lot of customers hit this and would prefer to have the conversion proceed despite the targets files, we can consider adding an opt-in switch.

**Comment by MaherJendoubi** [comment]
It makes sense to me too. Thank you both @mjrousos and @cartermp for your answers.

**Pull request merged**
